X0: 0.0
Y0: 0.0

x1: 4.25
y1: 0.0

x2: 4.25
y2: -2.5

x3: 2.2
y3: -2.5

x4: 4.25
y4: 0.0

x5: 4.25
y5: 0.0

x6: 0.0
y6: 0.0

x7: 2.55
y7: 1.35

x8: 4.35
y8: 1.35

x9: 4.35
y9: -0.25

x10: 3.25
y10: -0.25

x11: 3.25
y11: 0.2

x12: 0.0
y12: 0.0